INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "SHEILD Funding", "Charitable Works", 500000, 01-03-19, 08-09-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "Maria Stark Foundation", "Charitable Works", 1000000, 06-01-19, 06-30-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Make Cap a New Shield", "Inventions", 50000, 01-01-19, 03-31-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "HYDRA is Never Ok Initiative", "Activism", 25000, 01-01-19, 12-31-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "Avengers Christmas Calendar", "Charitable Works", 5000, 07-01-19, 11-01-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Committee to Declare Latveria a Rogue State", "Activism", 25000, 08-01-19, 12-31-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "Get Hawkeye a Less Crappy Apartment", "Personal", 5000, 11-01-19, 12-24-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "Stop Alien Invasions Now", "Activism", 2000, 02-15-19, 04-05-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "Mutants are People Too", "Activism", 30000, 03-20-19, 08-08-19);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "Compositional Analysis of Spiderman's Webs", "Personal", 2000, 04-20-19, 06-30-19);

INSERT INTO users (name, age) VALUES ("Clint Barton", 32);
INSERT INTO users (name, age) VALUES ("Tony Stark", 42);
INSERT INTO users (name, age) VALUES ("Nick Fury", 00);
INSERT INTO users (name, age) VALUES ("Steve Rogers", 35);
INSERT INTO users (name, age) VALUES ("Reed Richards", 50);
INSERT INTO users (name, age) VALUES ("Sue Storm", 47);
INSERT INTO users (name, age) VALUES ("Janet Van Dyne", 39);
INSERT INTO users (name, age) VALUES ("Hank Pym", 42);
INSERT INTO users (name, age) VALUES ("Sam Wilson", 35);
INSERT INTO users (name, age) VALUES ("Bucky Barnes", 36);
INSERT INTO users (name, age) VALUES ("Natasha Romanoff", 00);
INSERT INTO users (name, age) VALUES ("Sharon Carter", 32);
INSERT INTO users (name, age) VALUES ("Peter Parker", 28);
INSERT INTO users (name, age) VALUES ("Luke Cage", 38);
INSERT INTO users (name, age) VALUES ("Jessica Jones", 37);
INSERT INTO users (name, age) VALUES ("Carol Danvers", 38);
INSERT INTO users (name, age) VALUES ("Jessica Drew", 34);
INSERT INTO users (name, age) VALUES ("Maria Hill", 41);
INSERT INTO users (name, age) VALUES ("Charles Xavier", 87);
INSERT INTO users (name, age) VALUES ("Stephen Strange", 42);

INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100000, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10500, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2500, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 6, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 9, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 9, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 10, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 13, 9);